on: push

name: Robot Attention

jobs:
  send_message:
    name: Send Robot Attention
    runs-on: ubuntu-latest
    steps:
      - name: Prepare message content
        id: message
        run: |
          echo ::set-output name=CONTENT::"$GITHUB_ACTOR make a push on repo $GITHUB_REPOSITORY branch ${GITHUB_REF:11}.\nHooray!"
      - name: Post message
        env:
          ROBOT_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"msg_type":"text","content":{"text":"${{steps.message.outputs.CONTENT}}"}}' ${{ secrets.ROBOT_TOKEN }}
